import {readFile,writeFile} from 'node:fs/promises';
import {hashProductionFile,productionPlanHash,inspectProductionAssets,lintProduction,REVIEW_CATEGORIES,type ProductionPlan,type ProductionEvidence} from '../../../src/production/index';
const dir='.design/beneath-double-coat/penny-introduction';
const plan:ProductionPlan=JSON.parse(await readFile(`${dir}/staging.plan.json`,'utf8'));
plan.id='penny-breakfast';plan.title='Penny joins the breakfast conversation';
for(const asset of plan.assets)asset.sha256=await hashProductionFile(asset.path);
plan.facts.push(...Object.entries({'father':'The navy-collared adult is the puppy’s dad.','parents':'The green-collared adult is the puppy’s mother.','penny-named':'The daughter is Penny; her parents are arguing about father’s excuse.','cheese-request':'Penny asks for the same untouched cheese that drove the argument.','breakfast-closed':'Mother grants the cheese to Penny and closes the argument with a joke.'}).map(([id,description])=>({id,description})));
plan.dialogue=[{id:'trouble',speaker:'penny',text:'Dad, are you in trouble?'},{id:'breakfast',speaker:'bruno',text:'Your mother and I are discussing breakfast.'},{id:'subject',speaker:'sadie',text:'Penny, your father is changing the subject.'},{id:'cheese',speaker:'penny',text:'Then can I have his cheese?'},{id:'enough',speaker:'sadie',text:"Yes. He's had quite enough."}];
const definitions=[{id:'penny',seconds:8,position:'right' as const,eyeline:'Up left toward parents',cues:[{lineId:'trouble',start:0.6,end:2.8,visibility:'on-camera' as const},{lineId:'cheese',start:4.5,end:7.2,visibility:'on-camera' as const}]},{id:'bruno',seconds:5,position:'center' as const,eyeline:'Down right toward daughter',cues:[{lineId:'breakfast',start:0.6,end:3.7,visibility:'on-camera' as const}]},{id:'sadie',seconds:9,position:'left' as const,eyeline:'Right toward daughter',cues:[{lineId:'subject',start:0.6,end:3.7,visibility:'on-camera' as const},{lineId:'enough',start:5.2,end:7.7,visibility:'on-camera' as const}]}];
for(const def of definitions){
 const frame=`${def.id}-close`;plan.assets.push({id:frame,kind:'image',path:`${dir}/${frame}.jpg`,sha256:await hashProductionFile(`${dir}/${frame}.jpg`)});
 plan.assets.push({id:`${def.id}-performance`,kind:'video',path:`${dir}/${def.id}-performance.mp4`});
 const base=plan.takes[2];
 plan.takes.push({...base,id:`${def.id}-performance`,setupId:`${def.id}-to-family-close`,method:'first-frame',duration:def.seconds,assetId:`${def.id}-performance`,referenceAssetIds:[],firstFrame:{assetId:frame,fromTakeId:'family',at:def.id==='penny'?0.25:1.5},camera:{size:'close-up',angle:'Crop from actual accepted family master, same side of conversation axis',movement:'Locked camera'},cast:[{characterId:def.id,position:def.position,eyeline:def.eyeline}],actions:[{description:'Seated dog speaks using subtle canine jaw, eye and ear movements; no prop interaction.',risk:'low'}],dialogue:def.cues,sound:'Source-native voice of the one visible dog only, quiet room tone, no score or effects.'});
}
plan.shots=plan.shots.slice(1);
plan.shots[0].transition={...plan.shots[0].transition,type:'opening',reason:'Follow-on opens from exact accepted ending; first-frame provenance binds it to the preceding opening.'};
const specs=[['penny-first','penny-performance',0,3.5,'question',['puppy-visible'],['father','Puppy addresses the adult as Dad.','trouble']],['bruno-answer','bruno-performance',0,4.5,'answer',['father'],['parents','He explicitly mentions her mother.','breakfast']],['sadie-names','sadie-performance',0,4.3,'answer',['parents'],['penny-named','Mother names Penny and identifies her father.','subject']],['penny-cheese','penny-performance',4,8,'question',['penny-named'],['cheese-request','Penny asks for the established breakfast prop.','cheese']],['sadie-payoff','sadie-performance',4.8,8.8,'payoff',['cheese-request'],['breakfast-closed','Mother grants the request with a dry payoff.','enough']],['family-ending','family',1.5,3,'reaction',['breakfast-closed'],null]] as const;
for(const [id,takeId,start,end,purpose,requires,intro] of specs)plan.shots.push({id,takeId,in:start,out:end,purpose,requires:[...requires],establishes:intro?[{factId:intro[0],evidence:intro[1],lineId:intro[2]}]:[],transition:{type:'cut',reason:id==='penny-first'?'Move closer after the silent daughter reveal.':id==='family-ending'?'Return to same family master to resolve breakfast.':'Question or response motivates return to the same saved character performance.',bridge:id==='penny-first'?'gaze':id==='family-ending'?'reaction':'dialogue',stateExceptions:[]}});
const notes={exposition:'Attention and silent family reveal precede dialogue. Dad establishes father; his mother line establishes the married couple as parents; Sadie names Penny before the cheese payoff.',transitions:'Exact accepted endpoint seeds attention. Wide reveal follows gaze. Each single follows a question or response; all returns reuse the same saved take. End reuses the family master.',continuity:'All single first frames are crops of actual family footage at 1.5s. Same room, established collars, untouched cheese, seated positions. Parents now address daughter; these are deliberate new angles rather than false old-angle matches.',speakers:'Every dialogue take contains exactly one visible speaking dog. Penny has two child-voice lines, Sadie two adult-female lines, Bruno one baritone line. No overlapping or offscreen dialogue.',pacing:'Seven short edit beats after orientation; raw handles will be cut to measured speech. Five concise lines carry the daughter introduction and breakfast joke with no new mystery information.',motion:'No entering, walking, paw gestures, food handling or furniture contact. Only seated jaw/head/eye motion is needed.',sound:'Native dialogue and quiet room tone throughout. No music to restart across cuts; no additional voices. Source utterances will be independently measured before final cuts.'};
const evidence:ProductionEvidence={version:1,reviews:[{version:1,planHash:productionPlanHash(plan),stage:'plan',targetId:plan.id,reviewer:'Local agent editorial pre-mortem; source master and extracted frames inspected',checks:REVIEW_CATEGORIES.map(category=>({category,verdict:'pass',evidence:notes[category]}))}],speech:[]};
const report=lintProduction(plan,{stage:'plan',assets:await inspectProductionAssets(plan,'.'),evidence});
for(const [name,data] of [['production.plan',plan],['production.evidence',evidence],['production.plan-report',report]])await writeFile(`${dir}/${name}.json`,JSON.stringify(data,null,2)+'\n');
console.log(JSON.stringify(report,null,2));if(report.status!=='ready')process.exit(1);
const common='Photorealistic prestige dog soap opera, same warm snowy-estate breakfast scene as supplied actual video frame. Exactly ONE real Bernese Mountain Dog on camera, the exact one visible in the first frame. Preserve this exact head, markings, collar, age, background and framing. A single locked close-up, no cuts or camera movement. Dog remains seated, with small natural canine jaw motion synchronized to its OWN clearly audible voice, small expressive eye/ear motion and restrained head motion. No human face, body, hands, child, person, extra animal, second dog, text or subtitles. Canine anatomy remains canine, no human lips/teeth or human facial morph. No standing, gestures or props. NO narrator, offscreen speaker, added dialogue, music, laughter, barking or sound effects. Clean natural speech with quiet continuous room tone. Neutral English accent. Silent gaps mean mouth rests closed. Both scripted lines belong to this one dog, not different characters.';
const prompts={penny:`${common} PENNY is the small lavender-collared female PUPPY, not an adult. Her voice is a clear natural young girl's voice with curious, matter-of-fact delivery, not squeaky or cartoonishly high. She looks slightly UP and LEFT toward her parents, never into lens. At 0.6s say exactly: "Dad, are you in trouble?" Finish around 2.8s. Hold a listening expression, muzzle closed, until 4.5s. Then say exactly: "Then can I have his cheese?" Finish by 7.2s. End with a very small hopeful glance toward the table, without moving her body. Eight seconds total.`,bruno:`${common} BRUNO is the large adult male with navy collar. His voice is a warm adult MALE BARITONE, slightly sheepish and overly dignified, matching the prior breakfast exchange. He looks slightly DOWN and RIGHT to his daughter. At 0.6s say exactly: "Your mother and I are discussing breakfast." One conversational phrase, finish by 3.7s. Then close muzzle and hold a gently guilty look. Five seconds total; no other words.`,sadie:`${common} SADIE is the adult female with GREEN collar and narrow white blaze. Her voice is a controlled medium-low adult FEMALE voice, dry and precise with warm restrained wit, matching the prior breakfast exchange. She looks camera-RIGHT toward her daughter. At 0.6s say exactly: "Penny, your father is changing the subject." Finish around 3.7s. Hold a listening expression with closed muzzle until 5.2s. Then say exactly: "Yes. He's had quite enough." A crisp comic answer, finish by 7.7s, then a very slight satisfied head tilt. Nine seconds total.`};
await writeFile(`${dir}/performance-jobs.json`,JSON.stringify(definitions.map(def=>({id:`penny-sequence-${def.id}`,kind:'video',output:`${dir}/${def.id}-performance.mp4`,firstFrame:`${dir}/${def.id}-close.jpg`,seconds:def.seconds,prompt:prompts[def.id as keyof typeof prompts]})),null,2)+'\n');
