"use client";
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useAuth} from '@/lib/auth-context';
import {watchMyNarrations} from '@/lib/narrations';
import type {Narration} from '@/lib/types';
import {useWorkspace} from '@/components/shell/workspace-provider';
import {useSceneComposer} from './scene-composer-provider';
import {authenticatedVideoFetch} from './use-video-jobs';

export function AudioAssets(){
 const {user}=useAuth();const {draftId,state}=useWorkspace();const scene=useSceneComposer();const router=useRouter();const [items,setItems]=useState<Narration[]>([]);const [search,setSearch]=useState('');const [issue,setIssue]=useState('');const [preview,setPreview]=useState<{id:string;url:string}|null>(null);const [scope,setScope]=useState('all');
 useEffect(()=>user?watchMyNarrations(user.uid,setItems):undefined,[user]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview.url);},[preview]);
 const project=Object.values(state.projects??{}).find(p=>Object.keys(p.documents).some(href=>href===`/studio/scene?draft=${draftId}`));
 const ready=items.filter(item=>item.status==='ready'&&item.title.toLowerCase().includes(search.toLowerCase())&&(scope==='all'||!!project?.documents[`/narration/${item.id}`]));
 return <div className="grid gap-3 p-3"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">Narration</h3><Button size="icon-xs" variant="ghost" aria-label="Create narration for this video" onClick={()=>router.push(`/studio?draft=${crypto.randomUUID()}&video=${encodeURIComponent(draftId)}&at=${scene.playhead.toFixed(3)}`)}><Plus size={15}/></Button></div><Input aria-label="Search audio assets" placeholder="Search narration" value={search} onChange={e=>setSearch(e.target.value)}/>{project?<select aria-label="Asset scope" value={scope} onChange={e=>setScope(e.target.value)} className="rounded border border-border bg-background p-2 text-xs"><option value="all">All library</option><option value="project">This project</option></select>:null}<p className="text-xs text-ink-muted">Insert at {scene.playhead.toFixed(1)}s</p>{issue?<p role="alert" className="text-xs">{issue}</p>:null}{ready.map(item=><div key={item.id} className="grid gap-2 border-b border-border pb-3"><Link href={`/narration/${item.id}`} className="text-sm hover:underline">{item.title}</Link><span className="text-xs text-ink-muted">{(item.durationMs/1000).toFixed(1)}s / {item.voice}</span><div className="flex gap-2"><Button variant="outline" size="xs" onClick={async()=>{try{setIssue('');const response=await authenticatedVideoFetch(`/api/narrations/${item.id}/audio?raw=1`);setPreview({id:item.id,url:URL.createObjectURL(await response.blob())});}catch{setIssue('This audio could not be loaded. Try again.');}}}>Audition</Button><Button size="xs" variant="secondary" onClick={()=>{const id=crypto.randomUUID();scene.setAudioPlacements([...scene.audioPlacements,{id,narrationId:item.id,title:item.title,startSeconds:scene.playhead,inSeconds:0,outSeconds:item.durationMs/1000,volume:1,muted:false}]);scene.selectAudio(id);}}>Insert</Button></div>{preview?.id===item.id?<audio src={preview.url} controls autoPlay className="w-full"/>:null}</div>)}{!ready.length?<p className="text-xs text-ink-muted">No finished narration here. Create one to use as voiceover.</p>:null}<p className="text-xs text-ink-muted">Music and sound effects will use this same asset workflow when their generators are added.</p></div>;
}
export function AudioPlacementInspector(){
 const scene=useSceneComposer();const clip=scene.audioPlacements.find(c=>c.id===scene.selectedAudioId);const [issue,setIssue]=useState('');if(!clip)return null;
 const update=(patch:Partial<typeof clip>)=>scene.setAudioPlacements(scene.audioPlacements.map(c=>c.id===clip.id?{...c,...patch}:c));
 return <div className="grid gap-4 p-4"><h2 className="text-sm font-medium">{clip.title}</h2><Link href={`/narration/${clip.narrationId}`} className="text-xs underline">Open source narration</Link><form key={clip.id} className="grid gap-3" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const startSeconds=Number(data.get('start')),inSeconds=Number(data.get('in')),outSeconds=Number(data.get('out'));if(startSeconds<0||startSeconds>300||inSeconds<0||outSeconds-inSeconds<.05){setIssue('Choose a valid start and trim range.');return;}update({startSeconds,inSeconds,outSeconds});setIssue('');}}>{[['start','Start in video',clip.startSeconds],['in','Source in',clip.inSeconds],['out','Source out',clip.outSeconds]].map(([name,label,value])=><label key={name} className="grid gap-1 text-xs text-ink-muted">{label} (s)<Input name={String(name)} type="number" min="0" step="0.001" defaultValue={value}/></label>)}<Button size="sm" variant="outline">Apply timing</Button></form>{issue?<p role="alert" className="text-xs">{issue}</p>:null}<label className="grid gap-2 text-xs">Volume {Math.round(clip.volume*100)}%<input type="range" min="0" max="1" step="0.05" value={clip.volume} onChange={e=>update({volume:Number(e.target.value)})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={clip.muted} onChange={e=>update({muted:e.target.checked})}/>Mute</label><Button variant="ghost" size="sm" onClick={()=>{scene.setAudioPlacements(scene.audioPlacements.filter(c=>c.id!==clip.id));scene.selectAudio(null);}}>Remove from video</Button><p className="text-xs text-ink-muted">This placement uses a saved take. Source regeneration does not replace it.</p></div>;
}
export function SequenceAudio({time,playing}:{time:number;playing:boolean}){
 const {audioPlacements}=useSceneComposer();const [urls,setUrls]=useState<Record<string,string>>({});const [issue,setIssue]=useState('');const elements=useRef(new Map<string,HTMLAudioElement>());const ids=[...new Set(audioPlacements.map(c=>c.narrationId))].sort().join(',');
 useEffect(()=>{let active=true;const owned:string[]=[];void Promise.all(ids.split(',').filter(Boolean).map(async id=>{try{const response=await authenticatedVideoFetch(`/api/narrations/${id}/audio?raw=1`);const url=URL.createObjectURL(await response.blob());owned.push(url);if(active)setUrls(current=>({...current,[id]:url}));else URL.revokeObjectURL(url);}catch{if(active)setIssue('A narration could not be loaded for preview. Open its source to check access.');}}));return()=>{active=false;owned.forEach(URL.revokeObjectURL);};},[ids]);
 useEffect(()=>{for(const clip of audioPlacements){const audio=elements.current.get(clip.id);if(!audio)continue;const target=time-clip.startSeconds+clip.inSeconds;const within=time>=clip.startSeconds&&target<clip.outSeconds;audio.volume=Math.min(1,clip.volume);audio.muted=clip.muted;if(!within||!playing)audio.pause();if(within&&audio.readyState>=1){if(Math.abs(audio.currentTime-target)>.2)audio.currentTime=target;if(playing)void audio.play().catch(()=>setIssue('Press play again to enable audio preview.'));}}},[time,playing,audioPlacements,urls]);
 return <>{audioPlacements.map(clip=>urls[clip.narrationId]?<audio key={`${clip.id}:${urls[clip.narrationId]}`} ref={node=>{if(node)elements.current.set(clip.id,node);else elements.current.delete(clip.id);}} src={urls[clip.narrationId]} preload="auto"/>:null)}{issue?<p role="status" className="text-xs text-ink-muted">{issue}</p>:null}</>;
}
