"use client";
import {PlacementControls} from './placement-controls';
import {placementNeedsRecording} from '@/lib/script-timeline';
import {useRef,useState} from 'react';
import {Camera} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {CAMERA_MOVES,insertCameraPhrase} from '@/lib/scene-direction';
import {beatDuration} from '@/lib/scene-tracks';
import {useSceneComposer} from './scene-composer-provider';
import {BeatGenerationFeedback} from './beat-generation-feedback';
import {useWorkspace} from '@/components/shell/workspace-provider';
import {scriptContinuity} from '@/lib/script-continuity';
export function BeatTrackInspector({canGenerate}:{canGenerate:boolean}){
 const {state,draftId}=useWorkspace();const record=state.sceneDrafts[draftId];const continuous=!!record?.builtScript&&scriptContinuity(record.videoBrief,record.builtScript)==='continuous';
 const scene=useSceneComposer();const track=scene.tracks.find(t=>t.beat.id===scene.selectedBeatId);const input=useRef<HTMLTextAreaElement>(null);const selection=useRef({start:0,end:0});const [issue,setIssue]=useState('');const [camera,setCamera]=useState(false);
 if(!track)return <p className="p-4 text-sm text-ink-muted">Add a beat and write its direction to begin.</p>;
 const index=scene.tracks.indexOf(track),duration=beatDuration(track.beat);const previous=scene.tracks.find(t=>t.beat.id===track.previousBeatId),next=scene.tracks.slice(index+1).find(t=>t.included);
 const updateText=(text:string)=>scene.updateDraft({beats:scene.draft.beats.map(b=>b.id===track.beat.id?{...b,text}:b)});
 const blocked=!track.busy&&track.continuationIssue;
 return <div className="grid gap-4 p-4"><header className="flex items-center justify-between"><h2 className="text-sm font-medium">Beat {String(index+1).padStart(2,'0')}</h2><span className="font-mono text-xs text-ink-muted">{track.start.toFixed(1)}–{track.end.toFixed(1)}s</span></header>
 <PlacementControls key={track.beat.id} track={track}/>
 {!placementNeedsRecording(track.clip)?<select aria-label="Selected beat generation mode" className="rounded border border-border bg-surface-inset p-2 text-sm" value={track.generationMode} disabled={continuous||track.busy||scene.batchRunning} onChange={e=>scene.updateBeatClip(track.beat.id,{generationMode:e.target.value as 'new'|'continue'})}><option value="new">New shot</option><option value="continue" disabled={!previous}>Continues Beat {String(previous?scene.tracks.indexOf(previous)+1:1).padStart(2,'0')}</option></select>:null}
 <div className="grid gap-2"><div className="flex items-center justify-between"><label htmlFor="beat-direction" className="text-xs text-ink-muted">Direction</label><Popover open={camera} onOpenChange={setCamera}><PopoverTrigger asChild><Button variant="ghost" size="xs"><Camera size={13}/>Camera</Button></PopoverTrigger><PopoverContent align="end" className="grid gap-1">{CAMERA_MOVES.map(move=><Button key={move.id} variant="ghost" size="sm" onClick={()=>{const result=insertCameraPhrase(track.beat.text,selection.current.start,selection.current.end,move.phrase);updateText(result.text);setCamera(false);}}>{move.label}</Button>)}</PopoverContent></Popover></div><Textarea id="beat-direction" ref={input} aria-label="Selected beat direction" value={track.beat.text} rows={6} onChange={e=>updateText(e.target.value)} onSelect={e=>{selection.current={start:e.currentTarget.selectionStart,end:e.currentTarget.selectionEnd};}}/></div>
 {blocked?<div className="grid gap-2"><p role="status" className="text-xs text-ink-muted">{blocked}</p>{previous&&Math.abs(previous.trim.end-previous.sourceEnd)>.001?<Button size="sm" variant="outline" onClick={()=>scene.updateBeatClip(previous.beat.id,{outSeconds:previous.sourceEnd})}>Restore previous ending</Button>:null}</div>:null}
 {!placementNeedsRecording(track.clip)?<div className="flex items-center justify-between gap-2"><Button variant="secondary" size="sm" disabled={!!track.clip?.pendingVideoId||track.busy||scene.batchRunning||duration>40||!(track.generationMode==='continue'?scene.ready&&!blocked:canGenerate)} onClick={()=>void scene.generateBeat(track.beat.id)}>{track.busy?'Generating':track.job?.canContinue&&track.matches?'Finish beat':track.clip?.videoId?'Regenerate beat':'Generate beat'}</Button>{!track.busy&&!track.issue&&!blocked?<span className="text-xs text-ink-muted">{track.ready?'Ready':track.needsContinuation?'Needs continuation':track.job&&!track.matches?'Direction changed':'Not generated'}</span>:null}</div>:null}
 {track.busy||track.issue||track.job?.status==='error'||track.job?.status==='partial'?<><BeatGenerationFeedback track={track}/>{track.clip?.videoId?<Button variant="ghost" size="xs" onClick={()=>scene.reloadJob(track.clip!.videoId!)}>Check status</Button>:null}</>:null}
 <details className="border-t border-border pt-3"><summary className="cursor-pointer text-sm">Clip settings</summary><div className="mt-4 grid gap-4">{track.url?<form key={`${track.beat.id}:${track.trim.start}:${track.trim.end}`} className="grid gap-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),start=Number(f.get('in')),end=Number(f.get('out'));if(start<track.sourceStart||end>track.sourceEnd||end-start<.05){setIssue('Keep trims inside the saved beat range.');return;}scene.updateBeatClip(track.beat.id,{inSeconds:start,outSeconds:end});setIssue('');}}><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs">In (s)<Input name="in" type="number" step="0.001" defaultValue={Number(track.trim.start.toFixed(3))}/></label><label className="grid gap-1 text-xs">Out (s)<Input name="out" type="number" step="0.001" defaultValue={Number(track.trim.end.toFixed(3))}/></label></div><Button size="sm" variant="outline">Apply trim</Button>{issue?<p role="alert" className="text-xs">{issue}</p>:null}{Math.abs(track.trim.end-track.sourceEnd)>.001?<Button type="button" variant="ghost" size="xs" onClick={()=>scene.updateBeatClip(track.beat.id,{outSeconds:track.sourceEnd})}>Restore original ending</Button>:null}</form>:null}
 <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={!!track.clip?.muted} onChange={e=>scene.updateBeatClip(track.beat.id,{muted:e.target.checked})}/>Mute clip audio</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={track.included} onChange={e=>scene.updateBeatClip(track.beat.id,{excluded:!e.target.checked})}/>Include in video</label><div className="flex gap-2"><Button size="xs" variant="outline" disabled={!index} onClick={()=>scene.moveBeat(track.beat.id,-1)}>Earlier</Button><Button size="xs" variant="outline" disabled={index===scene.tracks.length-1} onClick={()=>scene.moveBeat(track.beat.id,1)}>Later</Button></div><label className="grid gap-2 text-xs">Transition to next beat<select id="beat-transition-control" aria-label="Selected beat transition" disabled={continuous||!next||!track.included} value={track.transition} className="rounded border border-border bg-background p-2" onChange={e=>scene.updateBeatClip(track.beat.id,{transition:e.target.value as 'cut'|'fade',transitionSeconds:.5})}><option value="cut">Hard cut</option><option value="fade">Fade</option></select></label>{track.transition==='fade'?<label className="grid gap-1 text-xs">Fade length (s)<Input aria-label="Fade length in seconds" type="number" min="0.05" max={Math.min(track.trim.duration,next?.trim.duration??0)/2} step="0.05" value={track.transitionSeconds} onChange={e=>{const value=Number(e.target.value);if(value>0)scene.updateBeatClip(track.beat.id,{transitionSeconds:Math.min(value,Math.min(track.trim.duration,next?.trim.duration??0)/2)});}}/></label>:null}{track.sourceVideoId&&track.url?<Button size="xs" variant="ghost" onClick={()=>scene.downloadJob(track.sourceVideoId!)}>Download take</Button>:null}</div></details>
 </div>;
}
