"use client";
import {VideoBriefEditor} from './video-brief';
import {useState,useEffect} from 'react';
import {Film,Plus,Maximize2} from 'lucide-react';
import {WorkbenchPanel} from '@/components/shell/workbench-panel';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {useSceneComposer} from './scene-composer-provider';
import {useWorkspace} from '@/components/shell/workspace-provider';
import {SceneTracks} from './scene-tracks';
import {BeatEditor} from './beat-editor';
import {BeatTrackInspector} from './beat-track-inspector';
import {SceneGenerationSettings} from './scene-generation-settings';
import {AudioAssets,AudioPlacementInspector} from './audio-assets';
import './scene-composer.css';
export function SceneComposer(){
 const scene=useSceneComposer();const {activeTab,store,state,draftId}=useWorkspace();const [briefViews,setBriefViews]=useState<Record<string,boolean>>({});const showBrief=briefViews[draftId]??(!state.sceneDrafts[draftId]?.builtScript&&!Object.values(state.sceneDrafts[draftId]?.beatClips??{}).some(clip=>clip.videoId));const setShowBrief=(value:boolean)=>setBriefViews(current=>({...current,[draftId]:value}));const [panel,setPanel]=useState<'beats'|'assets'>('beats');const [mobileView,setMobileView]=useState<'preview'|'details'|'assets'>('preview');const [settings,setSettings]=useState(false);const [exportReview,setExportReview]=useState(false);const [focus,setFocus]=useState(false);
 useEffect(()=>{if(activeTab)store.updateTab(activeTab.id,{title:scene.title});},[activeTab,store,scene.title]);
 const included=scene.tracks.filter(t=>t.included),busy=included.some(t=>t.busy)||scene.batchRunning,missing=included.some(t=>!t.ready);const attachments=scene.draft.mode==='text'||scene.draft.mode==='image'&&!!scene.firstFrame||scene.draft.mode==='references'&&scene.references.length>0;
 const addBeat=()=>{scene.updateDraft({beats:[...scene.draft.beats,{id:crypto.randomUUID(),start:null,end:null,text:''}]});setFocus(true);};
 return <WorkbenchPanel title="Video" icon={<Film size={15}/>} bodyClassName="video-document-body" actions={<><Button variant="outline" size="xs" onClick={()=>setShowBrief(!showBrief)}>{showBrief?'Open editor':'Brief and script'}</Button>{!showBrief?<><Button variant="ghost" size="xs" onClick={()=>setSettings(true)}>Scene settings</Button><Button size="sm" disabled={!included.length||missing||scene.exporting||busy} onClick={()=>state.sceneDrafts[draftId]?.builtScript?setExportReview(true):void scene.exportScene()}>{scene.exporting?'Exporting':'Export video'}</Button></>:null}</>}>
 {showBrief?<VideoBriefEditor key={draftId} onBuilt={()=>setShowBrief(false)}/>:<div className="scene-composer video-document"><div className="video-document-toolbar"><Input aria-label="Video title" value={scene.title} onChange={e=>scene.setTitle(e.target.value)} className="max-w-60 border-transparent bg-transparent text-sm"/><span role="status" className="text-xs text-ink-muted">{scene.exportIssue||scene.batchIssue||scene.batchProgress||(scene.exporting?'Assembling video':`${included.filter(t=>t.ready).length} of ${included.length} beats ready`)}</span>{scene.exportUrl?<Button variant="ghost" size="xs" onClick={()=>scene.downloadJob(scene.exportJob!.id)}>{scene.exportCurrent?'Download export':'Download earlier export'}</Button>:null}<Button size="xs" variant="outline" disabled={!!state.sceneDrafts[draftId]?.builtScript&&!missing||!included.some(t=>!t.clip?.placement||t.clip.placement.source==='generated')||busy||!attachments||included.some(t=>!!t.clip?.pendingVideoId)} onClick={()=>void (state.sceneDrafts[draftId]?.builtScript||missing?scene.generateMissingBeats():scene.regenerateAllBeats())}>{busy?'Generating':state.sceneDrafts[draftId]?.builtScript?(!missing?'Video ready':included.some(t=>t.ready)?'Continue building':'Build video'):missing?'Generate beats':'Regenerate all beats'}</Button></div>
 <nav className="video-mobile-nav" aria-label="Video panels">{(['preview','details','assets'] as const).map(view=><Button key={view} size="xs" variant={mobileView===view?'secondary':'ghost'} onClick={()=>{setMobileView(view);if(view==='assets')setPanel('assets');}}>{view==='preview'?'Preview':view==='details'?'Beat details':'Assets'}</Button>)}<Button variant="ghost" size="xs" onClick={()=>setFocus(true)}>Direction</Button></nav>
 <SceneTracks mobileView={mobileView} onAddBeat={addBeat} onAddAudio={()=>{setPanel('assets');setMobileView('assets');}} sidebar={<><div className="flex gap-1 border-b border-border p-2"><Button size="xs" variant={panel==='beats'?'secondary':'ghost'} onClick={()=>setPanel('beats')}>Beats</Button><Button size="xs" variant={panel==='assets'?'secondary':'ghost'} onClick={()=>setPanel('assets')}>Assets</Button></div>{panel==='assets'?<AudioAssets/>:<div className="grid gap-1 p-2">{scene.draft.beats.map((beat,index)=><button key={beat.id} aria-pressed={scene.selectedBeatId===beat.id&&!scene.selectedAudioId} onClick={()=>{scene.selectBeat(beat.id);scene.setPlayhead(scene.tracks.find(track=>track.beat.id===beat.id)?.start??0);if(!beat.text.trim())setFocus(true);}} className="grid gap-1 rounded p-3 text-left text-xs hover:bg-secondary aria-pressed:bg-secondary"><span>Beat {String(index+1).padStart(2,'0')}</span><span className="line-clamp-2 text-ink-muted">{scene.tracks.find(track=>track.beat.id===beat.id)?.clip?.placement?.visual||beat.text||'Write direction'}</span></button>)}<Button variant="ghost" size="sm" onClick={addBeat}><Plus size={14}/>Add beat</Button><Button variant="ghost" size="sm" onClick={()=>setFocus(true)}><Maximize2 size={13}/>Focus writing</Button></div>}</>} inspector={scene.selectedAudioId?<AudioPlacementInspector/>:<BeatTrackInspector canGenerate={scene.ready&&attachments}/>}/>
 </div>}
 <Sheet open={exportReview} onOpenChange={setExportReview}><SheetContent side="right"><SheetTitle>Export this sequence</SheetTitle><SheetDescription>The export uses the included video takes, source audio and attached audio tracks. Generated clips include their dialogue and sound.</SheetDescription><p className="text-sm">{included.length} video sections / {scene.audioPlacements.length} additional audio placements. Preview the sequence to check the sound before exporting.</p><Button disabled={missing||busy||scene.exporting} onClick={()=>{setExportReview(false);void scene.exportScene();}}>Export current picture and audio</Button></SheetContent></Sheet>
 <Sheet open={settings} onOpenChange={setSettings}><SheetContent side="right" className="w-[380px] p-0"><SheetTitle className="sr-only">Scene settings</SheetTitle><SheetDescription className="sr-only">Frame, generation inputs and shared direction</SheetDescription><div className="min-h-0 flex-1 overflow-y-auto"><SceneGenerationSettings settingsOnly/></div><label className="grid gap-2 p-4 text-xs">Shared continuity direction<textarea className="rounded border border-border bg-background p-3" rows={4} value={scene.draft.note} onChange={e=>scene.updateDraft({note:e.target.value})}/></label></SheetContent></Sheet>
 <Sheet open={focus} onOpenChange={setFocus}><SheetContent side="right" className="w-full overflow-y-auto sm:max-w-3xl"><SheetTitle>Scene direction</SheetTitle><SheetDescription>Edit all beats together. Close to return to the timeline.</SheetDescription><BeatEditor beats={scene.draft.beats} note={scene.draft.note} onChange={scene.updateDraft} focusWriting onFocusWriting={setFocus}/></SheetContent></Sheet>
 </WorkbenchPanel>;
}
