"use client";
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {ImportedProject,SavedProjects} from '@/components/projects/imported-project';
import Link from 'next/link';
import {FolderOpen,Plus} from 'lucide-react';
import {WorkbenchPanel} from '@/components/shell/workbench-panel';
import {useWorkspace} from '@/components/shell/workspace-provider';
import {CreateMenu} from '@/components/shell/create-menu';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function ProjectsPage(){
 const importedId=useSearchParams().get('import');
 const {state,store}=useWorkspace();const [name,setName]=useState('');const [selected,setSelected]=useState('');const [managing,setManaging]=useState(false);
 const documents=[...new Map([...Object.entries(state.sceneDrafts).map(([id,saved])=>({href:`/studio/scene?draft=${id}`,title:saved.title||saved.draft.beats.find(b=>b.text.trim())?.text.slice(0,65)||'Untitled video',type:'Video'})),...Object.entries(state.drafts).map(([id,saved])=>({href:`/studio?draft=${id}`,title:saved.markdown?.split('\n')[0].replace(/^#+\s*/,'').slice(0,65)||'Untitled narration',type:'Narration'})),...state.tabs.filter(tab=>tab.href.startsWith('/narration/')).map(tab=>({href:tab.href,title:tab.title,type:'Narration'})),...Object.values(state.projects??{}).flatMap(project=>Object.entries(project.documents).map(([href,title])=>({href,title,type:href.includes('/scene')?'Video':'Narration'})))].map(document=>[document.href,document])).values()];
 const project=state.projects?.[selected];
 if(importedId)return <WorkbenchPanel title="Production plan" bodyClassName="p-6"><div className="mx-auto w-full max-w-5xl"><ImportedProject id={importedId}/></div></WorkbenchPanel>;
 return <WorkbenchPanel title="Projects" icon={<FolderOpen size={15}/>} actions={<CreateMenu/>} bodyClassName="p-6"><div className="mx-auto grid w-full max-w-5xl gap-6"><SavedProjects/><div><h1 className="t-h2">Your work</h1><p className="mt-2 text-sm text-ink-muted">Create independently, or collect related documents in a project. Projects and drafts are saved in this browser.</p></div><form className="flex max-w-md gap-2" onSubmit={event=>{event.preventDefault();if(!name.trim())return;const id=crypto.randomUUID();store.setProject({id,name:name.trim(),documents:{}});setSelected(id);setName('');}}><Input aria-label="Project name" placeholder="New project name" value={name} onChange={e=>setName(e.target.value)}/><Button variant="outline" disabled={!name.trim()}><Plus size={14}/>Create project</Button></form><nav className="flex flex-wrap gap-2" aria-label="Project filter"><Button variant={!project?'secondary':'ghost'} onClick={()=>setSelected('')}>All documents</Button>{Object.values(state.projects??{}).map(item=><Button key={item.id} variant={item.id===selected?'secondary':'ghost'} onClick={()=>{setSelected(item.id);setManaging(false);}}>{item.name}</Button>)}</nav>{project?<div className="flex items-center gap-3"><label htmlFor="project-name" className="text-sm">Project name</label><Input id="project-name" className="max-w-xs" value={project.name} onChange={e=>store.setProject({...project,name:e.target.value})}/><Button size="sm" variant="outline" onClick={()=>setManaging(!managing)}>{managing?'Done':'Add documents'}</Button></div>:null}<div className="divide-y divide-border border-y border-border">{documents.filter(document=>!project||managing||project.documents[document.href]).map(document=><div key={document.href} className="flex items-center gap-4 py-4"><span className="w-20 text-xs text-ink-muted">{document.type}</span><Link href={document.href} className="min-w-0 flex-1 truncate text-sm hover:underline">{document.title}</Link>{project?<label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={!!project.documents[document.href]} onChange={e=>{const docs={...project.documents};if(e.target.checked)docs[document.href]=document.title;else delete docs[document.href];store.setProject({...project,documents:docs});}}/>In project</label>:null}</div>)}</div>{!documents.length?<p className="text-sm text-ink-muted">Create a narration or video to start your first document.</p>:null}</div></WorkbenchPanel>;
}
