import {readFile,writeFile} from 'node:fs/promises';
import {createGeminiClient} from '../src/tts/gemini-client-factory';
const dir='.design/beneath-double-coat/bruno-introduction';
const prompt=`Create ONE photorealistic cinematic first frame for the next shot of the SAME scene. Image1 is the actual accepted room footage and is the authority for architecture, amber wood tone, floorboards, winter daylight and camera-side lighting. Image2 is BRUNO's individual identity reference.
Camera remains inside the room on the same side, aiming more tightly toward the WOODEN DOOR BEHIND OTTO ON THE RIGHT OF IMAGE1. Show that paneled doorway now open and Bruno already paused at the threshold. Keep the same doorway wood panel design, vertical warm timber wall, floorboard direction, daylight from the LEFT and warmer interior light from above. Beyond the doorway is a dim empty wood hall, not a different grand mansion. Frame medium close, dog eye level: Bruno's face, navy collar and broad chest clearly visible, forequarters naturally grounded. A narrow strip of the established room wall/floor provides matching context. The closed snowy window can be cropped entirely out.
Exactly ONE visible character: BRUNO, the specific long-haired tricolor BERNESE MOUNTAIN DOG from Image2. Large adult male, navy blue collar, broad white chest, symmetrical rust eyebrows, white blaze, floppy ears. Mouth resting closed. Body faces slightly into room; eyes look toward screen LEFT, where Grandmother Heidi is offscreen. No movement or prop manipulation.
Heidi and Otto from Image1 are OUTSIDE THIS TIGHT FRAME; do not copy them into this image or replace them with people. No humans, other dogs, puppies, silhouettes, reflections, portraits or background diners. No captions, split screen, panels, labels, or new furniture. Single full-frame 16:9 image. This must look like a neighboring camera angle in Image1's room, not a newly invented room.`;
await writeFile(`${dir}/doorway-prompt.txt`,prompt);
const parts=[];for(const f of ['accepted-room.jpg','bruno-reference.jpg'])parts.push({inlineData:{mimeType:'image/jpeg',data:(await readFile(`${dir}/${f}`)).toString('base64')}});parts.push({text:prompt});
const r=await createGeminiClient().models.generateContent({model:'gemini-3.1-flash-image',contents:parts,config:{responseModalities:['IMAGE'],imageConfig:{aspectRatio:'16:9'}}});const p=r.candidates?.[0]?.content?.parts?.find(p=>p.inlineData)?.inlineData;if(!p?.data)throw Error('No image returned');await writeFile(`${dir}/doorway-first-frame.jpg`,Buffer.from(p.data,'base64'));console.log('Saved doorway-first-frame.jpg',p.mimeType);
